// SPDX-FileCopyrightText: 2026 rsh1k
// SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Quilzo-Commercial

package automate

// Templates are rules worth having, ready to add. Each starts in the mode
// it is safest in: what stops a sign-in acts, because it is undone by the
// person proving who they are; what changes another system asks first.
var Templates = []Rule{
	{ID: "tpl-impossible-travel", Name: "Impossible travel: make them prove it is them",
		Mode: "act", When: "signin",
		If:   []Condition{{Field: "signal", Op: "is", Value: "impossible-travel"}},
		Then: []Step{{Action: "step-up"}, {Action: "notify", With: map[string]string{"to": "security"}}},
		Note: "A sign-in further from the last than a plane could go gets no session until the person confirms it, and the security team is told."},
	{ID: "tpl-high-risk", Name: "A high-risk sign-in: make them prove it is them",
		Mode: "act", When: "signin",
		If:   []Condition{{Field: "risk", Op: "at-least", Value: "high"}},
		Then: []Step{{Action: "step-up"}, {Action: "notify", With: map[string]string{"to": "security"}}},
		Note: "High is impossible travel, Tor, a session that moved, or three unfamiliar things at once: the combinations Entra, Okta and Duo treat as a different person."},
	{ID: "tpl-anonymous", Name: "Through Tor or a hosting provider: step up",
		Mode: "act", When: "signin",
		If:   []Condition{{Field: "signal", Op: "one-of", Value: "anonymous-network,hosting-network"}},
		Then: []Step{{Action: "step-up"}},
		Note: "People sign in from home, work and phones; phishing proxies and scripts run on rented servers and Tor. A company VPN declared as such is never counted."},
	{ID: "tpl-session-moved", Name: "A session moved to another device or country: make them prove it",
		Mode: "act", When: "signin",
		If:   []Condition{{Field: "signal", Op: "is", Value: "session-moved"}},
		Then: []Step{{Action: "step-up"}, {Action: "notify", With: map[string]string{"to": "security"}}},
		Note: "A session cookie copied by malware and used elsewhere: the way past every sign-in check, and the one stolen sessions leave a trace of."},
	{ID: "tpl-reported", Name: "Somebody says a sign-in was not them: sign them out everywhere",
		Mode: "act", When: "person",
		If:   []Condition{{Field: "reason", Op: "is", Value: "reported"}},
		Then: []Step{{Action: "end-sessions"}, {Action: "open-case"}, {Action: "notify", With: map[string]string{"to": "security"}}},
		Note: "The person themselves is the best detector there is (Entra's \"user reported suspicious activity\")."},
	{ID: "tpl-verification-failing", Name: "Confirming it keeps failing: tell the security team",
		Mode: "act", When: "signin",
		If:   []Condition{{Field: "signal", Op: "is", Value: "verification-failing"}},
		Then: []Step{{Action: "notify", With: map[string]string{"to": "security"}}},
		Note: "Somebody guessing codes, or pushing until somebody gives in, as in the 2022 Uber breach."},
	{ID: "tpl-new-country-admin", Name: "An administrator signs in from a new country: step up",
		Mode: "act", When: "signin",
		If:   []Condition{{Field: "signal", Op: "is", Value: "new-country"}, {Field: "role", Op: "is", Value: "admin"}},
		Then: []Step{{Action: "step-up"}},
		Note: "Administrators are worth the extra check; everybody else is not asked every time they travel."},
	{ID: "tpl-leaver-active", Name: "A leaver can still sign in: suspend them in Okta",
		Mode: "ask", When: "finding",
		If:   []Condition{{Field: "source", Op: "is", Value: "estate/leaver-still-active"}},
		Then: []Step{{Action: "okta-suspend-user"}, {Action: "end-sessions"}, {Action: "open-case"}},
		Note: "Somebody HR says has left still has an active account. Suspending is undone by unsuspending; it waits for a person to agree."},
	{ID: "tpl-critical-case", Name: "A critical finding: open a case",
		Mode: "act", When: "finding",
		If:   []Condition{{Field: "severity", Op: "at-least", Value: "critical"}},
		Then: []Step{{Action: "open-case"}, {Action: "notify", With: map[string]string{"to": "security"}}},
		Note: "Nothing critical waits in a queue for somebody to notice it."},
	{ID: "tpl-unencrypted", Name: "An unencrypted machine: tell its owner",
		Mode: "act", When: "device",
		If:   []Condition{{Field: "control", Op: "is", Value: "disk-encryption"}},
		Then: []Step{{Action: "notify", With: map[string]string{"to": "person"}}},
		Note: "Most unencrypted laptops are fixed by the person who owns them, once somebody asks."},
	{ID: "tpl-phished", Name: "Somebody typed a password into a phish: end their sessions",
		Mode: "ask", When: "finding",
		If: []Condition{{Field: "source", Op: "is", Value: "estate/phished-untrained"},
			{Field: "title", Op: "contains", Value: "entered data"}},
		Then: []Step{{Action: "end-sessions"}, {Action: "okta-clear-sessions"}, {Action: "notify", With: map[string]string{"to": "person"}}},
		Note: "Only those who typed something in, not everybody who clicked: what they typed may already be in use. Ending their sessions is undone by signing in again."},
	// What other systems report, the moment they report it: Okta event
	// hooks and shared signals (CAEP and RISC) use the same names.
	{ID: "tpl-signal-session-revoked", Name: "Their session was ended elsewhere: end it here too",
		Mode: "act", When: "signal",
		If:   []Condition{{Field: "type", Op: "is", Value: "session-revoked"}},
		Then: []Step{{Action: "end-sessions"}},
		Note: "When the identity provider ends a session — the person signed out, an administrator cleared it, a policy revoked it — a session here that the same sign-in started should not outlive it. The CAEP session-revoked event exists for exactly this."},
	{ID: "tpl-signal-compromised", Name: "A credential was compromised elsewhere: make them prove it is them",
		Mode: "act", When: "signal",
		If:   []Condition{{Field: "type", Op: "one-of", Value: "credential-compromise,account-credential-change-required"}},
		Then: []Step{{Action: "step-up"}, {Action: "open-case"}, {Action: "notify", With: map[string]string{"to": "security"}}},
		Note: "A provider that knows a password leaked (RISC credential-compromise) is telling everybody who trusts it. Whoever holds the leaked one should not keep a session here on the strength of it."},
	{ID: "tpl-signal-high-risk", Name: "The identity provider rates them high risk: make them prove it is them",
		Mode: "act", When: "signal",
		If:   []Condition{{Field: "type", Op: "one-of", Value: "risk-level-change,threat"}, {Field: "current_level", Op: "at-least", Value: "high"}},
		Then: []Step{{Action: "step-up"}, {Action: "notify", With: map[string]string{"to": "security"}}},
		Note: "Okta's and other providers' risk engines see far more sign-ins than this site does; a high rating from them is worth a check here."},
	{ID: "tpl-signal-disabled", Name: "Their account was disabled elsewhere: sign them out here",
		Mode: "act", When: "signal",
		If:   []Condition{{Field: "type", Op: "one-of", Value: "account-disabled,account-purged"}},
		Then: []Step{{Action: "end-sessions"}, {Action: "notify", With: map[string]string{"to": "security"}}},
		Note: "A leaver suspended in the identity provider at five should not still be signed in here at six."},
	{ID: "tpl-signal-reported", Name: "They reported suspicious activity in the identity provider: sign them out and open a case",
		Mode: "act", When: "signal",
		If:   []Condition{{Field: "type", Op: "is", Value: "reported"}},
		Then: []Step{{Action: "end-sessions"}, {Action: "open-case"}},
		Note: "The person themselves is the best detector there is; Okta's end-user notifications ask them, and this acts on the answer here as well."},
	{ID: "tpl-signal-device", Name: "Their device stopped being compliant: tell them",
		Mode: "act", When: "signal",
		If:   []Condition{{Field: "type", Op: "is", Value: "device-compliance-change"}, {Field: "current_status", Op: "is", Value: "not-compliant"}},
		Then: []Step{{Action: "notify", With: map[string]string{"to": "person"}}},
		Note: "From an MDM such as Jamf over shared signals. Most devices are fixed by their owner once somebody says so."},
}
