// Package media accepts files without accepting what is inside them.
//
// # The controls, and which one this gets for free
//
// OWASP names four controls that have to work together for uploads: replace the
// caller's filename with one the server generates, validate content with a
// format-specific parser rather than magic bytes, store files somewhere the web
// server will not execute them, and serve them from a separate origin.
//
// Three of those fall out of the architecture rather than being added to it.
// Content is addressed by the SHA-256 of its bytes, so the stored name is
// generated by definition and no caller-supplied string ever becomes a path —
// which retires filename traversal, null bytes, `.php.jpg`, Windows reserved
// names and case-folding collisions in one go. Storage is the same object store
// the content uses: opaque blobs, no extensions, nothing a web server would
// dispatch on.
//
// The fourth, a separate origin, cannot be given by a library. What is done
// instead is documented on Serve, and the honest summary is that the sandbox
// headers are a mitigation and a second origin is the fix.
//
// # Magic bytes are not validation
//
// A polyglot satisfies a magic-byte check and is also something else. The GIFAR
// was a GIF and a JAR; a JPEG can carry a valid ZIP after its end marker. So
// every accepted format is *decoded* here, not sniffed. An image has to parse
// as an image and report plausible dimensions. A PDF has to have a header, a
// trailer, and no construct that makes a viewer do work.
//
// # What is refused outright
//
// SVG. It is XML that browsers execute: <script> works, so do event handlers,
// external references and entity expansion, and ImageTragick showed the
// server-side half. A sanitiser for it is a permanent commitment to tracking
// every new way to say "script" in XML, and this is a CMS, not a research
// project. PNG, JPEG and WebP cover what SVG is usually used for; anything that
// truly needs SVG can go through a person who understands what they are
// pasting.
//
// HTML, JavaScript, and anything the server could be persuaded to execute, for
// the reason that needs no elaboration.
package media

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"image"
	_ "image/gif"
	_ "image/jpeg"
	_ "image/png"
	"strings"
	"time"
	"unicode/utf8"
)

// Kind is a category of accepted file.
type Kind string

const (
	Image    Kind = "image"
	Video    Kind = "video"
	Audio    Kind = "audio"
	Document Kind = "document"
	Text     Kind = "text"
)

// Format is one accepted file format.
type Format struct {
	// MIME is what will be served. Taken from this table, never from the
	// upload: a caller-supplied Content-Type is a request, not a fact.
	MIME string
	Kind Kind
	// Ext is appended to download names only. It is never part of a stored
	// path, because nothing caller-influenced is.
	Ext string
	// Magic are the byte prefixes that may start this format.
	Magic [][]byte
	// MaxBytes bounds this format specifically. A 200 MB PNG is not a
	// photograph, it is a decompression bomb with a header.
	MaxBytes int64
	// Verify decodes the file properly. Returning an error refuses it.
	Verify func([]byte) error
	// Inline says the browser may render it directly. Everything else is sent
	// as an attachment, so a format this package does not fully understand
	// cannot become a page in the site's own origin.
	Inline bool
}

const (
	maxImage    = 24 << 20  // 24 MiB
	maxDocument = 64 << 20  // 64 MiB
	maxAV       = 512 << 20 // 512 MiB
	maxText     = 4 << 20   // 4 MiB
)

// MaxPixels bounds decoded image area.
//
// A 64000x64000 PNG compresses to a few kilobytes and decodes to about twelve
// gigabytes. The file-size limit does not catch it, because the file is small;
// the pixel count is the thing that has to be bounded. 50 megapixels is beyond
// any camera someone is likely to upload from.
const MaxPixels = 50_000_000

var formats = map[string]Format{
	"png": {
		MIME: "image/png", Kind: Image, Ext: ".png", MaxBytes: maxImage,
		Inline: true,
		Magic:  [][]byte{{0x89, 'P', 'N', 'G', 0x0D, 0x0A, 0x1A, 0x0A}},
		Verify: verifyImage,
	},
	"jpeg": {
		MIME: "image/jpeg", Kind: Image, Ext: ".jpg", MaxBytes: maxImage,
		Inline: true,
		Magic:  [][]byte{{0xFF, 0xD8, 0xFF}},
		Verify: verifyImage,
	},
	"gif": {
		MIME: "image/gif", Kind: Image, Ext: ".gif", MaxBytes: maxImage,
		Inline: true,
		Magic:  [][]byte{[]byte("GIF87a"), []byte("GIF89a")},
		Verify: verifyImage,
	},
	"webp": {
		MIME: "image/webp", Kind: Image, Ext: ".webp", MaxBytes: maxImage,
		Inline: true,
		// RIFF....WEBP — the size field sits between, so the check is split.
		Magic:  [][]byte{[]byte("RIFF")},
		Verify: verifyWebP,
	},
	"pdf": {
		MIME: "application/pdf", Kind: Document, Ext: ".pdf", MaxBytes: maxDocument,
		// Not inline. A PDF renders in the site's own origin with a scripting
		// engine attached, and PDF JavaScript is a real thing.
		Magic:  [][]byte{[]byte("%PDF-")},
		Verify: verifyPDF,
	},
	// Audio and video are inline.
	//
	// They were attachments, which is the setting for a format this program
	// cannot reason about — and it shipped a video section kind that puts one
	// of these in a page. A browser ignores Content-Disposition on a media
	// subresource, so the section worked by accident; a reader following a
	// direct link got a download of a file called 3a2ca8bef9b8724d.mp4.
	//
	// The risk class is the image's, not the PDF's: these are handed to a media
	// decoder, not to a scripting engine, and every one of them is decoded
	// here before it is stored.
	"mp4": {
		MIME: "video/mp4", Kind: Video, Ext: ".mp4", MaxBytes: maxAV,
		Inline: true,
		Magic:  [][]byte{},
		Verify: verifyISOBMFF,
	},
	"webm": {
		MIME: "video/webm", Kind: Video, Ext: ".webm", MaxBytes: maxAV,
		Inline: true,
		Magic:  [][]byte{{0x1A, 0x45, 0xDF, 0xA3}}, // EBML
		Verify: verifyEBML,
	},
	"mp3": {
		MIME: "audio/mpeg", Kind: Audio, Ext: ".mp3", MaxBytes: maxAV,
		Inline: true,
		Magic:  [][]byte{[]byte("ID3"), {0xFF, 0xFB}, {0xFF, 0xF3}, {0xFF, 0xF2}},
		Verify: verifyMP3,
	},
	"ogg": {
		MIME: "audio/ogg", Kind: Audio, Ext: ".ogg", MaxBytes: maxAV,
		Inline: true,
		Magic:  [][]byte{[]byte("OggS")},
		Verify: func(b []byte) error { return nil },
	},
	"wav": {
		MIME: "audio/wav", Kind: Audio, Ext: ".wav", MaxBytes: maxAV,
		Inline: true,
		Magic:  [][]byte{[]byte("RIFF")},
		Verify: verifyWAV,
	},
	"txt": {
		MIME: "text/plain; charset=utf-8", Kind: Text, Ext: ".txt",
		MaxBytes: maxText, Magic: [][]byte{}, Verify: verifyUTF8,
	},
	"md": {
		MIME: "text/plain; charset=utf-8", Kind: Text, Ext: ".md",
		MaxBytes: maxText, Magic: [][]byte{}, Verify: verifyUTF8,
	},
	"csv": {
		MIME: "text/plain; charset=utf-8", Kind: Text, Ext: ".csv",
		MaxBytes: maxText, Magic: [][]byte{}, Verify: verifyCSV,
	},
}

// refused names formats that are deliberately not accepted, and why.
//
// Kept as data so the refusal can explain itself. "Unsupported file type" sends
// people looking for a converter that produces the same risk under a different
// extension.
var refused = map[string]string{
	"svg": "SVG is XML that browsers execute — script elements, event handlers, " +
		"external references and entity expansion all work, and ImageTragick " +
		"was the server-side half. Export it as PNG or WebP.",
	"html": "HTML uploaded into the site's own origin is stored cross-site " +
		"scripting with extra steps. Write a page instead.",
	"htm":   "See html.",
	"xhtml": "See html.",
	"js":    "There is no case where a CMS needs to accept executable script as content.",
	"mjs":   "See js.",
	"wasm":  "See js.",
	"php":   "The server does not execute uploads, and it is going to stay that way.",
	"jsp":   "See php.",
	"asp":   "See php.",
	"aspx":  "See php.",
	"phtml": "See php.",
	"exe": "An executable is not content. Nothing here runs uploads, but a " +
		"site that hosts one becomes the distribution point for it.",
	"dll": "See exe.",
	"so":  "See exe.",
	"sh":  "See exe.",
	"bat": "See exe.",
	"jar": "A JAR is a ZIP, and the GIFAR made a file that was a valid GIF and " +
		"a valid JAR at once. Archives are not accepted at all.",
	"zip": "An archive hides its contents from every check performed here. " +
		"Upload the files.",
	"gz":  "See zip.",
	"tar": "See zip.",
	"rar": "See zip.",
	"7z":  "See zip.",
	"docx": "An Office document is a ZIP of XML with macro and external-entity " +
		"history. Export it as PDF.",
	"doc":  "See docx.",
	"xlsx": "See docx.",
	"xls":  "See docx.",
	"pptx": "See docx.",
	"ppt":  "See docx.",
	"xml": "XML uploaded as content is an entity-expansion and external-entity " +
		"surface with no upside here.",
	"ico": "ICO parsing has a long history of integer overflows and no use as " +
		"page content.",
	"tiff": "TIFF has an enormous parser surface and no browser support.",
	"tif":  "See tiff.",
	"bmp":  "BMP header arithmetic is a classic overflow. Convert to PNG.",
	"psd": "A Photoshop document is a working file, not something a browser " +
		"can display. Export the flattened image as PNG or WebP.",
	"eps":     "EPS is PostScript, which is a programming language.",
	"ps":      "See eps.",
	"pdf.exe": "See exe.",
}

// File is an accepted upload, after validation.
type File struct {
	// ID is the SHA-256 of the bytes: the server-generated name, and also the
	// deduplication key. Uploading the same photograph twice stores it once.
	ID string `json:"id"`
	// Name is the caller's filename, kept for display only. It is never a path
	// and never influences storage.
	Name string `json:"name"`
	// Format is the key in the table above, so the MIME type served comes from
	// the table rather than from anything the caller said.
	Format string `json:"format"`
	Kind   Kind   `json:"kind"`
	Size   int64  `json:"size"`
	// Width and Height are set for images, and are what the templates need to
	// emit intrinsic dimensions — which is what stops a page reflowing as
	// images load.
	Width  int `json:"width,omitempty"`
	Height int `json:"height,omitempty"`
	// Alt is the description. Required before an image may be used on a page:
	// WCAG 1.1.1, enforced at the point the image is attached rather than
	// checked afterwards.
	Alt string `json:"alt,omitempty"`
	// Source records where it came from when it was imported rather than
	// uploaded, so provenance survives the round trip.
	Source string `json:"source,omitempty"`

	// Rights is what permits publishing this, and until when. See rights.go:
	// an image licence is a publish window pointed at a file, and the reason
	// it is here rather than in a spreadsheet is that a licence which lapses
	// is a publishing event nothing otherwise notices.
	Rights Rights `json:"rights,omitempty"`

	// Supersedes is the file this one replaced, if any.
	//
	// Versioning falls out of content addressing — the old bytes are still
	// stored under their own hash and nothing can overwrite them — but that
	// only preserves the file, not the fact that it was replaced. A page still
	// pointing at last season's packaging shot is not a corrupted store, it is
	// a store where nobody recorded that a newer one exists.
	Supersedes string `json:"supersedes,omitempty"`

	UploadedAt int64  `json:"uploaded_at"`
	UploadedBy string `json:"uploaded_by,omitempty"`
}

// MIME returns the type this file will be served as.
func (f File) MIME() string {
	if fm, ok := formats[f.Format]; ok {
		return fm.MIME
	}
	return "application/octet-stream"
}

// Inline reports whether a browser may render this directly.
func (f File) Inline() bool {
	fm, ok := formats[f.Format]
	return ok && fm.Inline
}

// DownloadName is a safe filename for Content-Disposition.
//
// Rebuilt from the id and the format's own extension rather than sanitised from
// the caller's string. Sanitising is a blocklist, and blocklists lose: a
// filename can carry newlines that split the header, quotes that end the
// parameter, semicolons that add one, or RTL overrides that make evil.exe.png
// display as evil.gnp.exe.
func (f File) DownloadName() string {
	ext := ""
	if fm, ok := formats[f.Format]; ok {
		ext = fm.Ext
	}
	return f.ID[:16] + ext
}

// Accept validates bytes and returns the file record.
//
// name is used only to pick which format to try, and only as a hint: the bytes
// have the final say. A file called photo.png that does not decode as a PNG is
// refused, and a file called photo.txt that is a PNG is accepted as a PNG.
func Accept(name string, body []byte, now time.Time) (File, error) {
	if len(body) == 0 {
		return File{}, fmt.Errorf("the file is empty")
	}

	ext := extensionOf(name)
	if why := WhyRefused(ext); why != "" {
		return File{}, fmt.Errorf("%s files are not accepted. %s", ext, why)
	}

	key, fm, err := identify(ext, body)
	if err != nil {
		return File{}, err
	}
	if int64(len(body)) > fm.MaxBytes {
		return File{}, fmt.Errorf("%s is %s, over the %s limit for %s files",
			name, human(int64(len(body))), human(fm.MaxBytes), key)
	}
	if err := fm.Verify(body); err != nil {
		return File{}, fmt.Errorf("%s does not look like a valid %s: %w",
			name, key, err)
	}

	sum := sha256.Sum256(body)
	f := File{
		ID: hex.EncodeToString(sum[:]), Name: displayName(name),
		Format: key, Kind: fm.Kind, Size: int64(len(body)),
		UploadedAt: now.Unix(),
	}
	if fm.Kind == Image {
		if cfg, _, err := image.DecodeConfig(bytes.NewReader(body)); err == nil {
			f.Width, f.Height = cfg.Width, cfg.Height
		}
	}
	return f, nil
}

// identify picks a format from the bytes, using the extension only to choose
// which candidate to check first.
func identify(ext string, body []byte) (string, Format, error) {
	// An extension that names a known format has to be confirmed by the bytes.
	if fm, ok := formats[canonical(ext)]; ok {
		if matchesMagic(fm, body) {
			return canonical(ext), fm, nil
		}
	}
	// Otherwise try every format with a signature. Text formats have none, so
	// they are only reachable by extension — which is correct: bytes that are
	// merely valid UTF-8 should not be silently accepted as a text file.
	for key, fm := range formats {
		if len(fm.Magic) == 0 {
			continue
		}
		if matchesMagic(fm, body) {
			return key, fm, nil
		}
	}
	return "", Format{}, fmt.Errorf(
		"the contents do not match any accepted format. Accepted: %s",
		strings.Join(Accepted(), ", "))
}

func matchesMagic(fm Format, body []byte) bool {
	if len(fm.Magic) == 0 {
		return true
	}
	for _, m := range fm.Magic {
		if bytes.HasPrefix(body, m) {
			return true
		}
	}
	return false
}

func canonical(ext string) string {
	switch ext {
	case "jpg", "jpeg":
		return "jpeg"
	case "htm":
		return "html"
	case "m4a", "m4v":
		return "mp4"
	}
	return ext
}

func extensionOf(name string) string {
	name = strings.ToLower(strings.TrimSpace(name))
	// Every dotted segment is checked, not just the last: `shell.php.png` is
	// dangerous on a server configured to dispatch on any of them, and the
	// refusal list should see the php.
	parts := strings.Split(name, ".")
	if len(parts) < 2 {
		return ""
	}
	for _, p := range parts[1:] {
		if _, bad := refused[p]; bad {
			return p
		}
	}
	return parts[len(parts)-1]
}

// displayName keeps something readable without keeping anything dangerous.
func displayName(name string) string {
	name = strings.TrimSpace(name)
	// Strip any directory component: only the last segment can be a name, and
	// both separators are handled because an upload can come from either.
	if i := strings.LastIndexAny(name, "/\\"); i >= 0 {
		name = name[i+1:]
	}
	var b strings.Builder
	for _, r := range name {
		switch {
		case r < 0x20 || r == 0x7f:
			// Control characters, including the NUL that truncates a C string
			// and the newline that splits an HTTP header.
			continue
		case r >= 0x202A && r <= 0x202E, r >= 0x2066 && r <= 0x2069:
			// Bidirectional overrides. These make `evil.exe.png` display as
			// `evil.gnp.exe`, which is a filename that lies to a person.
			continue
		default:
			b.WriteRune(r)
		}
	}
	out := strings.TrimSpace(b.String())
	if out == "" {
		return "unnamed"
	}
	if len(out) > 120 {
		out = out[:120]
	}
	return out
}

// Accepted lists the formats that are allowed.
func Accepted() []string {
	out := make([]string, 0, len(formats))
	for k := range formats {
		out = append(out, k)
	}
	sortStrings(out)
	return out
}

// WhyRefused explains a rejected extension, or empty if it is not on the list.
//
// Cross-references are resolved rather than returned. The table says "See php."
// to keep the list readable, but a person shown "See php." has been told
// nothing — they cannot see the table. So the reference is followed once and
// the real reason comes back with a note about which entry it came from.
func WhyRefused(ext string) string {
	ext = strings.ToLower(strings.TrimPrefix(strings.TrimSpace(ext), "."))
	why, ok := refused[ext]
	if !ok {
		return ""
	}
	if ref, isRef := strings.CutPrefix(why, "See "); isRef {
		ref = strings.TrimSuffix(strings.TrimSpace(ref), ".")
		if target, found := refused[ref]; found && !strings.HasPrefix(target, "See ") {
			return target + " (" + ext + " is refused for the same reason as " +
				ref + ")"
		}
	}
	return why
}

func human(n int64) string {
	switch {
	case n >= 1<<20:
		return fmt.Sprintf("%.0f MB", float64(n)/(1<<20))
	case n >= 1<<10:
		return fmt.Sprintf("%.0f kB", float64(n)/(1<<10))
	}
	return fmt.Sprintf("%d bytes", n)
}

func sortStrings(s []string) {
	for i := 1; i < len(s); i++ {
		for j := i; j > 0 && s[j] < s[j-1]; j-- {
			s[j], s[j-1] = s[j-1], s[j]
		}
	}
}

// -- verifiers ---------------------------------------------------------------

// verifyImage decodes the header properly rather than trusting the signature.
//
// DecodeConfig reads enough to know the dimensions without allocating the
// pixels, which is what makes the bomb check possible: the size is known before
// anything large is allocated.
func verifyImage(b []byte) error {
	cfg, _, err := image.DecodeConfig(bytes.NewReader(b))
	if err != nil {
		return fmt.Errorf("it does not decode: %w", err)
	}
	if cfg.Width <= 0 || cfg.Height <= 0 {
		return fmt.Errorf("it reports %dx%d pixels", cfg.Width, cfg.Height)
	}
	// The decompression bomb. A 64000x64000 PNG is a few kilobytes on disk and
	// about twelve gigabytes decoded, so the file-size limit does not see it.
	if px := int64(cfg.Width) * int64(cfg.Height); px > MaxPixels {
		return fmt.Errorf(
			"it is %dx%d, which is %d megapixels — a small file that decodes to "+
				"gigabytes is a decompression bomb, not a photograph",
			cfg.Width, cfg.Height, px/1_000_000)
	}
	return nil
}

func verifyWebP(b []byte) error {
	// RIFF____WEBP: the four bytes at offset 8 distinguish it from a WAV, which
	// also starts RIFF. Without this a WAV would be served as an image and a
	// WebP as audio, depending only on which extension was claimed.
	if len(b) < 16 || !bytes.Equal(b[8:12], []byte("WEBP")) {
		return fmt.Errorf("it starts as a RIFF container but is not WebP")
	}
	return nil
}

func verifyWAV(b []byte) error {
	if len(b) < 16 || !bytes.Equal(b[8:12], []byte("WAVE")) {
		return fmt.Errorf("it starts as a RIFF container but is not WAVE")
	}
	return nil
}

// verifyPDF checks structure and refuses the constructs that make a viewer act.
//
// Not a full parser, and it does not claim to be. What it does is refuse the
// features with no legitimate place in a document being published on a website:
// embedded JavaScript, automatic actions, launch actions, and embedded files.
// A PDF that needs those is not a document, it is a program.
func verifyPDF(b []byte) error {
	if !bytes.HasPrefix(b, []byte("%PDF-")) {
		return fmt.Errorf("no PDF header")
	}
	// The trailer is at the end. Its absence means truncated or crafted, and
	// either way a viewer will do something unpredictable with it.
	tail := b
	if len(tail) > 2048 {
		tail = tail[len(tail)-2048:]
	}
	if !bytes.Contains(tail, []byte("%%EOF")) {
		return fmt.Errorf("no end-of-file marker; it is truncated or crafted")
	}

	for _, danger := range []struct{ token, why string }{
		{"/JavaScript", "it contains JavaScript"},
		{"/JS", "it contains JavaScript"},
		{"/Launch", "it contains a launch action, which starts a program"},
		{"/OpenAction", "it runs an action when opened"},
		{"/AA", "it runs an action on an event"},
		{"/EmbeddedFile", "it has another file embedded in it"},
		{"/RichMedia", "it embeds media with its own runtime"},
		{"/XFA", "it is an XFA form, which is XML with a scripting engine"},
	} {
		if bytes.Contains(b, []byte(danger.token)) {
			return fmt.Errorf("%s (%s). A document being published should not "+
				"do anything when opened", danger.why, danger.token)
		}
	}
	return nil
}

// verifyISOBMFF checks the MP4 box structure.
//
// An MP4 has no fixed prefix — it begins with a size, then "ftyp". Checking at
// offset 4 rather than 0 is the difference between validating the format and
// validating nothing.
func verifyISOBMFF(b []byte) error {
	if len(b) < 12 {
		return fmt.Errorf("too short to be a container")
	}
	if !bytes.Equal(b[4:8], []byte("ftyp")) {
		return fmt.Errorf("no ftyp box at offset 4")
	}
	brand := string(b[8:12])
	for _, ok := range []string{"isom", "iso2", "iso4", "iso5", "iso6", "mp41",
		"mp42", "avc1", "M4V ", "M4A ", "dash", "qt  "} {
		if brand == ok {
			return nil
		}
	}
	return fmt.Errorf("unrecognised brand %q", brand)
}

func verifyEBML(b []byte) error {
	if len(b) < 4 {
		return fmt.Errorf("too short")
	}
	// The DocType appears early and says whether this is WebM or Matroska.
	head := b
	if len(head) > 4096 {
		head = head[:4096]
	}
	if !bytes.Contains(head, []byte("webm")) && !bytes.Contains(head, []byte("matroska")) {
		return fmt.Errorf("an EBML container that is neither WebM nor Matroska")
	}
	return nil
}

// verifyMP3 refuses an ID3 tag carrying anything but audio metadata.
//
// CVE-2021-29447 was XXE reached through WordPress parsing ID3 tags on an
// uploaded audio file. Nothing here parses the tag, which is the point — but a
// tag containing a DOCTYPE is a file built to be parsed by something that does,
// and forwarding it on is how the next tool inherits the bug.
func verifyMP3(b []byte) error {
	if len(b) < 4 {
		return fmt.Errorf("too short")
	}
	if !bytes.HasPrefix(b, []byte("ID3")) {
		return nil // a bare frame sync, with no tag to worry about
	}
	head := b
	if len(head) > 1<<20 {
		head = head[:1<<20]
	}
	for _, bad := range [][]byte{
		[]byte("<!DOCTYPE"), []byte("<!ENTITY"), []byte("<?xml"), []byte("SYSTEM"),
	} {
		if bytes.Contains(head, bad) {
			return fmt.Errorf("its ID3 tag contains XML markup (%s). "+
				"CVE-2021-29447 was exactly this, reaching an XML parser through "+
				"an audio tag", bad)
		}
	}
	return nil
}

func verifyUTF8(b []byte) error {
	if !utf8.Valid(b) {
		return fmt.Errorf("it is not valid UTF-8")
	}
	// A NUL in text is either a binary file with a text extension or an attempt
	// to truncate a downstream C string.
	if bytes.IndexByte(b, 0) >= 0 {
		return fmt.Errorf("it contains a NUL byte, so it is not text")
	}
	return nil
}

// verifyCSV additionally refuses formula injection.
//
// A cell beginning =, +, - or @ is executed as a formula when the file is
// opened in a spreadsheet. The file is harmless where it sits and dangerous
// where it lands, which is the case people forget.
func verifyCSV(b []byte) error {
	if err := verifyUTF8(b); err != nil {
		return err
	}
	for i, line := range strings.Split(string(b), "\n") {
		if i > 5000 {
			break
		}
		for _, cell := range strings.Split(line, ",") {
			cell = strings.TrimLeft(cell, " \t\"'")
			if cell == "" {
				continue
			}
			switch cell[0] {
			case '=', '+', '@':
				return fmt.Errorf(
					"line %d has a cell starting %q, which a spreadsheet runs as "+
						"a formula when the file is opened", i+1, cell[0])
			case '\t', '\r':
				return fmt.Errorf("line %d has a cell starting with a control "+
					"character used to smuggle formulas past filters", i+1)
			}
		}
	}
	return nil
}
