// Package provenance records how each page came to exist, in the form the law
// now asks for.
//
// # Why this is not optional
//
// The EU AI Act's Article 50 transparency obligations took effect on 2 August
// 2026. Where an AI system generates content, the provider must apply a
// machine-readable mark identifying it as artificially generated, and the
// penalty for getting it wrong is up to EUR 15 million or 3% of worldwide
// turnover. scrivet ships an assistant that writes pages, so this is not a
// feature it would be nice to have — it is the condition for the assistant being
// usable by anyone publishing into the EU.
//
// There is an exemption worth reading carefully: content does not need marking
// where the AI "performs an assistive function for standard editing or does not
// substantially alter the input data or its semantics". Fixing a typo is
// assistive. Writing the page is not. The distinction is encoded in
// `SourceType` rather than left to whoever is filling in a form.
//
// # The vocabulary is not invented here
//
// The marking uses C2PA's `digitalSourceType`, taken from the IPTC vocabulary,
// which is what OpenAI, Google, Meta and Amazon already emit. Inventing a
// private scheme would produce a mark nothing else can read, which is the one
// thing a machine-readable mark must not be.
//
// # Binding, and why it differs from C2PA's
//
// C2PA embeds a signed manifest inside the asset. That works for a JPEG and it
// has a known weakness: strip the metadata and the claim is gone, silently.
//
// Here content is already immutable and addressed by the hash of its bytes, so a
// provenance record names the hash it describes. Two things follow. The record
// cannot drift from its content, because changing the content changes the
// address. And stripping the record is *detectable* rather than silent: the page
// resolves to a hash with no provenance, which `Check` reports as a gap instead
// of as human authorship.
//
// That last part matters more than it sounds. The dangerous failure is not a
// missing mark — it is a missing mark that reads as "a person wrote this".
package provenance

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"sort"
	"strings"
	"time"
)

// SourceType is the IPTC digitalSourceType, as used by C2PA.
//
// The full vocabulary is larger; these are the values a CMS can honestly
// distinguish. A value nobody can determine reliably is worse than no value,
// because it will be believed.
type SourceType string

const (
	// HumanEdits: a person wrote or edited it, with no model involved.
	HumanEdits SourceType = "humanEdits"

	// TrainedAlgorithmicMedia: generated by a model. This is the marking
	// Article 50 requires.
	TrainedAlgorithmicMedia SourceType = "trainedAlgorithmicMedia"

	// CompositeWithTrainedAlgorithmicMedia: a person's work with model-generated
	// parts, or model output a person then edited. Article 50 still applies.
	CompositeWithTrainedAlgorithmicMedia SourceType = "compositeWithTrainedAlgorithmicMedia"

	// AlgorithmicMedia: produced by software that is not a trained model — a
	// template, an import, a scripted migration. Deliberately distinct, because
	// calling a database import "AI-generated" devalues the mark that matters.
	AlgorithmicMedia SourceType = "algorithmicMedia"
)

// requiresDisclosure reports whether Article 50's marking obligation applies.
var requiresDisclosure = map[SourceType]bool{
	HumanEdits:                           false,
	AlgorithmicMedia:                     false,
	TrainedAlgorithmicMedia:              true,
	CompositeWithTrainedAlgorithmicMedia: true,
}

// Valid reports whether a source type is one this package knows.
func (s SourceType) Valid() bool { _, ok := requiresDisclosure[s]; return ok }

// RequiresDisclosure reports whether content of this type must be marked.
func (s SourceType) RequiresDisclosure() bool { return requiresDisclosure[s] }

func (s SourceType) Describe() string {
	switch s {
	case HumanEdits:
		return "written by a person"
	case TrainedAlgorithmicMedia:
		return "generated by an AI model"
	case CompositeWithTrainedAlgorithmicMedia:
		return "part AI-generated, part human"
	case AlgorithmicMedia:
		return "produced by software, not a trained model"
	}
	return "unrecorded"
}

// Record is the provenance of one page at one point in its history.
type Record struct {
	// ContentHash is the object id of the content this describes. The binding.
	ContentHash string `json:"content_hash"`

	SourceType SourceType `json:"digital_source_type"`

	// Model and Instruction are present when a model was involved. The
	// instruction is kept because "why does the page say that" is the question
	// people actually ask, and a model name alone does not answer it.
	Model       string `json:"model,omitempty"`
	Instruction string `json:"instruction,omitempty"`

	// Author is the person accountable, even when a model did the writing.
	// Article 50 puts the obligation on a provider or deployer, never on a tool.
	Author string `json:"author"`

	// ReviewedBy records a human who checked model output before publication.
	// Empty is meaningful: it says nobody did.
	ReviewedBy string `json:"reviewed_by,omitempty"`

	At   int64  `json:"at"`
	Note string `json:"note,omitempty"`
}

// Disclosure is the sentence a reader should see.
func (r *Record) Disclosure() string {
	if !r.SourceType.RequiresDisclosure() {
		return ""
	}
	who := r.Model
	if who == "" {
		who = "an AI model"
	}
	base := fmt.Sprintf("Parts of this page were generated by %s", who)
	if r.SourceType == TrainedAlgorithmicMedia {
		base = fmt.Sprintf("This page was generated by %s", who)
	}
	if r.ReviewedBy != "" {
		return base + fmt.Sprintf(" and reviewed by %s.", r.ReviewedBy)
	}
	// Said plainly. "Reviewed" and "not reviewed" are different claims and a
	// reader is entitled to the difference.
	return base + " and has not been reviewed by a person."
}

// Index maps page name to provenance, for one commit.
type Index struct {
	Records map[string]Record `json:"records"`
}

func NewIndex() *Index { return &Index{Records: map[string]Record{}} }

// Set records provenance for a page.
func (i *Index) Set(page string, r Record) error {
	if !r.SourceType.Valid() {
		return fmt.Errorf("%q is not a known digitalSourceType", r.SourceType)
	}
	if strings.TrimSpace(r.ContentHash) == "" {
		return fmt.Errorf("a provenance record must name the content it describes")
	}
	if strings.TrimSpace(r.Author) == "" {
		return fmt.Errorf(
			"a provenance record needs an accountable author; Article 50 places the " +
				"obligation on a person or organisation, never on the tool")
	}
	if r.At == 0 {
		r.At = time.Now().Unix()
	}
	if i.Records == nil {
		i.Records = map[string]Record{}
	}
	i.Records[page] = r
	return nil
}

// Get returns the record for a page.
func (i *Index) Get(page string) (Record, bool) {
	r, ok := i.Records[page]
	return r, ok
}

// Status is what Check found for one page.
type Status struct {
	Page       string
	Have       bool
	Stale      bool // a record exists but describes different content
	Record     Record
	NeedsMark  bool
	Disclosure string
}

// Check reconciles provenance against the content actually present.
//
// `pages` maps page name to the object id of its current content. Three outcomes
// matter and each is reported separately, because collapsing them is how a gap
// becomes a claim:
//
//	missing  no record at all — unknown provenance, not human authorship
//	stale    a record naming different bytes — it describes an older version
//	present  a record bound to exactly this content
func Check(idx *Index, pages map[string]string) []Status {
	names := make([]string, 0, len(pages))
	for n := range pages {
		names = append(names, n)
	}
	sort.Strings(names)

	out := make([]Status, 0, len(names))
	for _, name := range names {
		st := Status{Page: name}
		if r, ok := idx.Get(name); ok {
			st.Have = true
			st.Record = r
			st.Stale = r.ContentHash != pages[name]
			st.NeedsMark = r.SourceType.RequiresDisclosure()
			st.Disclosure = r.Disclosure()
		}
		out = append(out, st)
	}
	return out
}

// Unmarked lists pages that need an Article 50 mark and would not get one.
//
// Stale records count as unmarked. A record describing a previous version is
// evidence about that version, and treating it as covering the current one is
// exactly the error the hash binding exists to prevent.
func Unmarked(statuses []Status) []Status {
	var out []Status
	for _, s := range statuses {
		if !s.Have || s.Stale {
			out = append(out, s)
			continue
		}
	}
	return out
}

// -- what goes into the page ---------------------------------------------------

// MetaTags renders the machine-readable marking for an HTML page.
//
// Two forms, because they are read by different things. The meta tags are what a
// crawler or a browser extension looks for; the JSON-LD block is what a
// structured-data consumer parses. Neither is a substitute for the signed record
// in the store — they are the copy that travels with the page, and a copy that
// travels can be stripped.
func (r *Record) MetaTags() string {
	if r == nil {
		return ""
	}
	var b strings.Builder
	fmt.Fprintf(&b, "<meta name=\"c2pa:digitalSourceType\" content=\"%s\">\n",
		escapeAttr(string(r.SourceType)))
	if r.SourceType.RequiresDisclosure() {
		fmt.Fprintf(&b, "<meta name=\"ai-generated\" content=\"true\">\n")
		if r.Model != "" {
			fmt.Fprintf(&b, "<meta name=\"ai-model\" content=\"%s\">\n", escapeAttr(r.Model))
		}
		reviewed := "false"
		if r.ReviewedBy != "" {
			reviewed = "true"
		}
		fmt.Fprintf(&b, "<meta name=\"ai-human-reviewed\" content=\"%s\">\n", reviewed)
	}
	fmt.Fprintf(&b, "<meta name=\"content-hash\" content=\"sha256:%s\">\n",
		escapeAttr(r.ContentHash))
	return b.String()
}

// JSONLD renders the record as schema.org-shaped structured data.
func (r *Record) JSONLD() (string, error) {
	if r == nil {
		return "", nil
	}
	doc := map[string]any{
		"@context":            "https://schema.org",
		"@type":               "CreativeWork",
		"digitalSourceType":   string(r.SourceType),
		"sdDatePublished":     time.Unix(r.At, 0).UTC().Format(time.RFC3339),
		"creditText":          r.Author,
		"identifier":          "sha256:" + r.ContentHash,
		"isAccessibleForFree": true,
	}
	if r.SourceType.RequiresDisclosure() {
		doc["disclaimer"] = r.Disclosure()
		if r.Model != "" {
			doc["creator"] = map[string]any{"@type": "SoftwareApplication", "name": r.Model}
		}
	}
	b, err := json.MarshalIndent(doc, "", "  ")
	if err != nil {
		return "", err
	}
	return string(b), nil
}

// escapeAttr keeps a value inside a quoted HTML attribute.
//
// Provenance values come from a model instruction and a model name, both of
// which are attacker-influenced in the case this whole project assumes. A
// provenance mark that permits an attribute break-out would be an injection
// vector introduced by the compliance feature, which would be a poor joke.
func escapeAttr(s string) string {
	rep := strings.NewReplacer(
		"&", "&amp;", "<", "&lt;", ">", "&gt;", `"`, "&quot;", "'", "&#39;")
	return rep.Replace(s)
}

// Digest is a stable fingerprint of the index, for binding into a commit.
func (i *Index) Digest() string {
	b, err := json.Marshal(i.Records)
	if err != nil {
		return ""
	}
	// Marshal of a map sorts keys, so this is stable across runs.
	sum := sha256.Sum256(b)
	return hex.EncodeToString(sum[:])
}
