// SPDX-FileCopyrightText: 2026 Rashik Adhikari
// SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Quilzo-Commercial

package admin

import (
	"net/http"
	"net/url"
	"strings"
	"testing"

	"github.com/quilzo/quilzo/internal/auth"
)

// What is accepted is what the assistant wrote for this person, under the
// model that wrote it. A proposal written in the browser, a model name
// changed on the way back, or somebody else's proposal is refused before
// anything is written or recorded as a model's.
func TestOnlyTheProposalTheAssistantWroteIsAccepted(t *testing.T) {
	srv, tok := scoped(t,
		auth.Binding{Principal: "editor", Role: auth.RoleAdmin, Resource: "/"},
		auth.Binding{Principal: "other", Role: auth.RoleAdmin, Resource: "/"},
	)
	var saved, recorded []string
	srv.Assist = &Assist{
		Pages: func() (map[string]any, error) { return map[string]any{}, nil },
		Save: func(pages map[string]any, msg, by, base string) error {
			saved = append(saved, msg)
			return nil
		},
		Record: func(pages []string, model, by string) error {
			recorded = append(recorded, model)
			return nil
		},
	}
	proposal := `{"pages":{"news":{"title":"News","body":"Written by a model."}}}`
	seal := srv.sealProposal("editor", "small-model", proposal)
	form := func(model, prop, seal string) string {
		return "model=" + url.QueryEscape(model) + "&proposal=" + url.QueryEscape(prop) + "&seal=" + seal
	}

	for name, tc := range map[string]struct{ who, body string }{
		"no seal":             {"editor", form("small-model", proposal, "")},
		"another model named": {"editor", form("big-model", proposal, seal)},
		"pages changed":       {"editor", form("small-model", strings.Replace(proposal, "a model", "me", 1), seal)},
		"somebody else's":     {"other", form("small-model", proposal, seal)},
	} {
		w := postForm(t, srv, "/assist/accept", tok[tc.who], tc.body)
		if w.Code != http.StatusSeeOther || !strings.Contains(w.Header().Get("Location"), "e=") {
			t.Errorf("%s: answered %d to %s", name, w.Code, w.Header().Get("Location"))
		}
	}
	if len(saved)+len(recorded) != 0 {
		t.Fatalf("an unsealed proposal was written (%v) or recorded (%v)", saved, recorded)
	}

	w := postForm(t, srv, "/assist/accept", tok["editor"], form("small-model", proposal, seal))
	if w.Code != http.StatusSeeOther || strings.Contains(w.Header().Get("Location"), "e=") {
		t.Fatalf("the sealed proposal: %d %s", w.Code, w.Header().Get("Location"))
	}
	if len(recorded) != 1 || recorded[0] != "small-model" {
		t.Errorf("recorded as generated by %v, want small-model", recorded)
	}
}
