// SPDX-FileCopyrightText: 2026 Rashik Adhikari
// SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Quilzo-Commercial

// Command genicons writes internal/icons/icons_gen.go: a chosen set of
// Material Symbols (Google, Apache-2.0) in each style a site can choose,
// as the single path each SVG holds. Run it by hand; the program never
// fetches an icon.
//
//	go run ./scripts/genicons > internal/icons/icons_gen.go
package main

import (
	"fmt"
	"go/format"
	"io"
	"net/http"
	"os"
	"regexp"
	"sort"
	"strings"
	"sync"
	"time"
)

// names are the icons a site may use: what feature lists, steps, contact
// blocks and pricing tables reach for. A closed list, so a name in content
// is either one of these or nothing.
var names = []string{
	"accessibility_new", "account_balance", "add_circle", "analytics", "apartment", "arrow_forward",
	"article", "auto_awesome", "bolt", "brush", "build", "calendar_month", "call", "campaign",
	"celebration", "chat", "check_circle", "cloud", "cloud_upload", "code",
	"description", "devices", "directions_car", "done_all", "download", "eco", "edit", "encrypted",
	"favorite", "fingerprint", "fitness_center", "flight", "folder", "forum", "groups", "handshake",
	"health_and_safety", "history", "home", "image", "insights", "inventory_2", "key", "language",
	"lightbulb", "local_cafe", "local_shipping", "location_on", "lock", "mail", "map", "menu_book", "mic",
	"music_note", "notifications", "open_in_new", "palette", "payments", "person", "pets",
	"photo_camera", "psychology", "public", "receipt_long", "recycling", "redeem", "restaurant",
	"rocket_launch", "savings", "schedule", "school", "science", "search", "security", "sell",
	"settings", "shield", "shopping_cart", "smart_toy", "speed", "star", "stop_circle", "storefront", "sunny",
	"support_agent", "sync", "terminal", "thumb_up", "translate", "trending_up", "tune",
	"verified", "videocam", "visibility", "volume_up", "water_drop", "wifi", "workspace_premium",
}

var styles = []struct{ key, dir, suffix string }{
	{"rounded", "materialsymbolsrounded", "_24px.svg"},
	{"rounded-filled", "materialsymbolsrounded", "_fill1_24px.svg"},
	{"outlined", "materialsymbolsoutlined", "_24px.svg"},
	{"outlined-filled", "materialsymbolsoutlined", "_fill1_24px.svg"},
	{"sharp", "materialsymbolssharp", "_24px.svg"},
	{"sharp-filled", "materialsymbolssharp", "_fill1_24px.svg"},
}

var rePath = regexp.MustCompile(`<path d="([^"]+)"`)
var reSafe = regexp.MustCompile(`^[0-9MmLlHhVvCcSsQqTtAaZz .,-]+$`)

func main() {
	type job struct{ name, style, url string }
	var jobs []job
	for _, n := range names {
		for _, s := range styles {
			jobs = append(jobs, job{n, s.key, "https://raw.githubusercontent.com/google/material-design-icons/master/symbols/web/" +
				n + "/" + s.dir + "/" + n + s.suffix})
		}
	}
	out := map[string]map[string]string{}
	var mu sync.Mutex
	var wg sync.WaitGroup
	sem := make(chan struct{}, 8)
	client := &http.Client{Timeout: 30 * time.Second}
	failed := false
	for _, j := range jobs {
		wg.Add(1)
		go func(j job) {
			defer wg.Done()
			sem <- struct{}{}
			defer func() { <-sem }()
			res, err := client.Get(j.url)
			if err != nil || res.StatusCode != 200 {
				mu.Lock()
				status := 0
				if res != nil {
					status = res.StatusCode
				}
				fmt.Fprintf(os.Stderr, "%s %s: %v (status %d)\n", j.name, j.style, err, status)
				failed = true
				mu.Unlock()
				return
			}
			defer res.Body.Close()
			b, _ := io.ReadAll(io.LimitReader(res.Body, 64<<10))
			m := rePath.FindSubmatch(b)
			// Only path data: numbers and commands. Anything else is not
			// an icon this program will put on a page.
			if m == nil || !reSafe.Match(m[1]) {
				mu.Lock()
				fmt.Fprintf(os.Stderr, "%s %s: no usable path\n", j.name, j.style)
				failed = true
				mu.Unlock()
				return
			}
			mu.Lock()
			if out[j.name] == nil {
				out[j.name] = map[string]string{}
			}
			out[j.name][j.style] = string(m[1])
			mu.Unlock()
		}(j)
	}
	wg.Wait()
	if failed {
		os.Exit(1)
	}
	var b strings.Builder
	b.WriteString("// SPDX-FileCopyrightText: 2026 Rashik Adhikari\n")
	b.WriteString("// SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Quilzo-Commercial\n\n")
	b.WriteString("// Code generated by scripts/genicons. DO NOT EDIT.\n\n")
	b.WriteString("// Material Symbols, by Google, under the Apache License 2.0\n")
	b.WriteString("// (internal/admin/assets/icons/LICENSE). Only each SVG's path is kept.\n\n")
	b.WriteString("package icons\n\nvar paths = map[string]map[string]string{\n")
	keys := make([]string, 0, len(out))
	for k := range out {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		fmt.Fprintf(&b, "\t%q: {\n", k)
		for _, s := range styles {
			fmt.Fprintf(&b, "\t\t%q: %q,\n", s.key, out[k][s.key])
		}
		b.WriteString("\t},\n")
	}
	b.WriteString("}\n")
	src, err := format.Source([]byte(b.String()))
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	os.Stdout.Write(src)
}
