// SPDX-FileCopyrightText: 2026 rsh1k
// SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Quilzo-Commercial

package controls

// table is the statements. Titles are the catalogue's (SP 800-53 Rev 5,
// release 5.2.0). Rules, settings and parameters are joined in by All, so
// they are not repeated here.
var table = []Implementation{
	// -- access control -------------------------------------------------------
	{Control: "AC-2", Title: "Account Management", Responsibility: Shared,
		Statement: "Every person and program that acts holds a grant in one access policy (principal, role, scope, optional expiry, who granted it) and authenticates with a token, a passkey or single sign-on. Grants can end on a date; SCIM 2.0 provisioning creates, updates and deactivates people from the identity provider, and deactivation revokes their sessions. Tokens are issued per person or program, expire, and are listed with when each was last used.",
		Customer:  "Decides who is granted what, keeps the identity provider's directory current, and reviews the people and tokens screens.",
		Where:     []string{"quilzo auth", "quilzo token", "/people", "/provisioning", "internal/auth", "internal/scim"}},
	{Control: "AC-2(3)", Title: "Disable Accounts", Responsibility: Shared,
		Statement: "Grants and tokens carry an end date and stop working on it. Tokens never used, unused for a long time, or expired without being revoked are reported by the posture scan; a person deactivated in the identity provider is suspended through SCIM.",
		Customer:  "Sets end dates, acts on the stale-credential findings, and deprovisions leavers in the identity provider.",
		Where:     []string{"quilzo token stale", "/security", "internal/scim"}},
	{Control: "AC-2(5)", Title: "Inactivity Logout", Responsibility: Shared,
		Statement: "With session.idle set, a browser session to the admin that nobody has used for that long is revoked on its next request, and the person is told why. The page reports keys, clicks and scrolls at most every half minute and warns a minute before the end; a screen refreshing itself does not count as use.",
		Customer:  "Chooses the period, or declares it as the organisation's parameter.",
		Where:     []string{"internal/admin/idle.go", "/settings", "/security/parameters"}},
	{Control: "AC-2(7)", Title: "Privileged User Accounts", Responsibility: Shared,
		Statement: "Administration is a role of its own, and the security, compliance and log areas are separate grants that can be given as time-limited jobs (analyst, compliance, support, auditor). The posture scan reports more administrators than the deployment needs.",
		Customer:  "Keeps the administrators few and named.",
		Where:     []string{"quilzo auth grant WHO JOB --for 30d", "internal/auth"}},
	{Control: "AC-3", Title: "Access Enforcement", Responsibility: Quilzo,
		Statement: "One policy is evaluated for every action on every surface — the command line before a command runs, the admin before a screen renders or a form is accepted, the content API, and each machine-interface operation, which declares the role it needs and is refused without one. A deny wins wherever it sits, and a token's own limits narrow what its holder may do.",
		Where:     []string{"cmd/quilzo/privilege.go", "internal/auth", "internal/mcp"}},
	{Control: "AC-5", Title: "Separation of Duties", Responsibility: Shared,
		Statement: "A draft can require approvals from people other than its author before it publishes, and a change an agent wrote always needs a person. Changing the organisation's policy, a shield playbook, or releasing a held shield takes a second administrator. The audit log can be written by a separate account from the one that serves the admin.",
		Customer:  "Sets how many approvals publishing needs and runs the log writer as its own account.",
		Where:     []string{"review.required_approvals", "quilzo policy", "quilzo logd"}},
	{Control: "AC-6", Title: "Least Privilege", Responsibility: Shared,
		Statement: "Four roles (reader, author, publisher, admin), each grant scoped to a path, and tokens that can be narrower than their holder: read-only, one role lower, limited to paths, types or languages. An agent's declared capabilities are narrowed again by the token of whoever runs it, and an extension runs with an empty environment in a filesystem sandbox.",
		Customer:  "Grants the narrowest role that does the job.",
		Where:     []string{"internal/auth", "internal/agent", "internal/sandbox"}},
	{Control: "AC-6(2)", Title: "Non-privileged Access for Nonsecurity Functions", Responsibility: Shared,
		Statement: "An administrator can issue themselves a token with a lower role for everyday work, and the posture scan reports administrator tokens used where a lesser one would do.",
		Customer:  "Uses lower-role tokens for routine work and automation.",
		Where:     []string{"quilzo token issue --role"}},
	{Control: "AC-6(5)", Title: "Privileged Accounts", Responsibility: Shared,
		Statement: "Only a grant of the admin role can change access, settings, the policy, integrations or agents' declarations; the posture scan reports when too many people hold it.",
		Customer:  "Restricts the admin role to the people who administer.",
		Where:     []string{"cmd/quilzo/privilege.go"}},
	{Control: "AC-7", Title: "Unsuccessful Logon Attempts", Responsibility: Quilzo,
		Statement: "Failed sign-ins are counted per source address and per account over an hour. After the free attempts each further one is delayed, doubling to a maximum; past a ceiling nothing is accepted for the rest of the hour, and a hard lockout can hold it until an hour passes without an attempt. Repeated failures raise an audit alert, and the shield's sign-in playbook blocks a source that keeps guessing. The values are the organisation's parameters ac-07_odp.01-.05.",
		Where:     []string{"internal/throttle", "internal/shield", "auth.throttle.*"}},
	{Control: "AC-11", Title: "Device Lock", Responsibility: Customer,
		Statement: "Quilzo cannot lock a device. It ends an admin session nobody has used for session.idle, which covers an unlocked browser left open.",
		Customer:  "Locks devices through the operating system or device management."},
	{Control: "AC-12", Title: "Session Termination", Responsibility: Quilzo,
		Statement: "Every sign-in to the admin — by token, passkey or single sign-on — starts a session that ends after session.max (at most twelve hours), when the person signs out (the session is revoked, not forgotten), when the credential that started it is revoked, and after session.idle unused. The values are the organisation's parameter ac-12_odp.",
		Where:     []string{"internal/auth", "internal/admin"}},
	{Control: "AC-17", Title: "Remote Access", Responsibility: Shared,
		Statement: "The admin is a separate process from the public site, listens on loopback unless told otherwise, and every request to it is authenticated; the posture scan reports an admin exposed to the internet.",
		Customer:  "Decides how the admin is reached (VPN, private network or proxy) and with what single sign-on.",
		Where:     []string{"quilzo serve", "quilzo site"}},

	// -- audit and accountability --------------------------------------------
	{Control: "AU-2", Title: "Event Logging", Responsibility: Quilzo,
		Statement: "Sign-ins, refusals of credentials, content changes, publishing, approvals, configuration and policy changes, grants and revocations, agent declarations and runs, shield actions and machine-interface writes are recorded in the audit log.",
		Where:     []string{"internal/audit"}},
	{Control: "AU-3", Title: "Content of Audit Records", Responsibility: Quilzo,
		Statement: "Each record says what happened, to what, when (UTC), with what outcome, and who: the principal, whether a person, a service or an AI model (and which model), whether the identity was verified, and on whose behalf an agent acted. The client address is decided once, from trusted proxies only.",
		Where:     []string{"internal/audit", "internal/clientip"}},
	{Control: "AU-6", Title: "Audit Record Review, Analysis, and Reporting", Responsibility: Shared,
		Statement: "Detections run over the log and collected events and open findings; repeated authentication failures raise an alert; agent activity is summarised and agents that keep trying refused things are flagged. The log screen and the findings queue are where a person reviews them.",
		Customer:  "Reviews the findings queue and the log at the organisation's frequency.",
		Where:     []string{"/findings", "/logs", "/security/agents"}},
	{Control: "AU-8", Title: "Time Stamps", Responsibility: Shared,
		Statement: "Records carry UTC timestamps from the host clock. Publications can be timestamped by an RFC 3161 authority and anchored with OpenTimestamps, so their time does not rest on this machine's clock.",
		Customer:  "Keeps the host clock synchronised.",
		Where:     []string{"quilzo timestamp", "quilzo anchor"}},
	{Control: "AU-9", Title: "Protection of Audit Information", Responsibility: Shared,
		Statement: "The log is append-only and hash-chained; its Merkle tree heads are signed with Ed25519 and ML-DSA, so a change to any record or a removal is detected. Heads can be published outside the machine, and the log can be written by a separate account.",
		Customer:  "Publishes heads outside the machine and runs the log writer separately.",
		Where:     []string{"quilzo auditlog", "internal/audit"}},
	{Control: "AU-9(2)", Title: "Store on Separate Physical Systems or Components", Responsibility: Customer,
		Statement: "Quilzo publishes signed log heads to a destination outside the machine, which lets another system prove the log has not been rewritten.",
		Customer:  "Chooses and runs that destination, and backs up the log elsewhere."},
	{Control: "AU-9(3)", Title: "Cryptographic Protection", Responsibility: Quilzo,
		Statement: "Every record is chained by SHA-256 to the one before it, and tree heads are signed with Ed25519 and ML-DSA (FIPS 204); inclusion and consistency proofs can be checked offline.",
		Where:     []string{"internal/audit", "internal/translog"}},
	{Control: "AU-9(4)", Title: "Access by Subset of Privileged Users", Responsibility: Shared,
		Statement: "The log collector can run as its own account, so the process serving the admin can append to the log and cannot rewrite it; the posture scan reports when it does not.",
		Customer:  "Deploys the collector under its own account.",
		Where:     []string{"quilzo logd"}},
	{Control: "AU-10", Title: "Non-repudiation", Responsibility: Quilzo,
		Statement: "Signed log heads with inclusion proofs bind each record to the log at a point in time; publications are timestamped and anchored; content and media carry signed provenance.",
		Where:     []string{"internal/audit", "internal/anchor", "internal/timestamp", "internal/c2pa"}},
	{Control: "AU-11", Title: "Audit Record Retention", Responsibility: Shared,
		Statement: "The audit log is never pruned, so records are kept for any period the organisation declares (au-11_odp). Form submissions are kept for the period their form declares and then deleted by both servers.",
		Customer:  "Keeps backups of the store for as long as its records policy requires.",
		Where:     []string{"internal/audit", "internal/form"}},
	{Control: "AU-12", Title: "Audit Record Generation", Responsibility: Quilzo,
		Statement: "Every surface records through one function, so the command line, the admin, the API and the machine interface produce the same records; the posture scan reports a log that is empty after activity.",
		Where:     []string{"internal/audit"}},

	// -- assessment, configuration, contingency -------------------------------
	{Control: "CA-7", Title: "Continuous Monitoring", Responsibility: Quilzo,
		Statement: "The posture scan runs on the server's schedule, opens a finding for each new failure and closes it when fixed; this binary is checked hourly against the Go vulnerability database; chatbots and agents are evaluated against planted instructions.",
		Where:     []string{"quilzo posture scan", "quilzo self check", "quilzo eval"}},
	{Control: "CM-3", Title: "Configuration Change Control", Responsibility: Shared,
		Statement: "Every configuration change is recorded; a value weaker than the default needs a written reason that lapses in ninety days; the organisation's parameters change only by one administrator proposing and another approving; content changes can need approvals and are versioned.",
		Customer:  "Reviews proposed changes and approvals.",
		Where:     []string{"quilzo config", "quilzo policy", "/settings"}},
	{Control: "CM-5", Title: "Access Restrictions for Change", Responsibility: Shared,
		Statement: "Changing settings, the policy, access, integrations or code that runs takes the admin role; the store's files are written 0600 and the posture scan reports looser modes.",
		Customer:  "Restricts operating-system access to the store's directory.",
		Where:     []string{"cmd/quilzo/privilege.go"}},
	{Control: "CM-6", Title: "Configuration Settings", Responsibility: Shared,
		Statement: "Every setting is in one closed table with a safe default; a weaker value needs a recorded reason; one weakened by hand is put back; the organisation's declared parameters are floors no setting may go below, and a setting below one is raised and reported.",
		Customer:  "Declares the organisation's parameters and sets operational values within them.",
		Where:     []string{"internal/config", "internal/odp"}},
	{Control: "CM-7", Title: "Least Functionality", Responsibility: Quilzo,
		Statement: "What is not needed is off: extensions, agent cards and remote telemetry are off by default; the shield can switch a public feature off or to limited while it is under attack or affected by a flaw.",
		Where:     []string{"internal/shield", "ext.enabled"}},
	{Control: "CM-8", Title: "System Component Inventory", Responsibility: Quilzo,
		Statement: "The binary describes itself: a CycloneDX 1.6 bill of materials from its build information (the Go standard library is its only dependency) and an inventory of every cryptographic algorithm it uses.",
		Where:     []string{"quilzo compliance sbom", "quilzo compliance crypto", "/security/inventory"}},
	{Control: "CM-14", Title: "Signed Components", Responsibility: Shared,
		Statement: "An extension runs only when it matches the SHA-256 recorded when it was registered; the running binary is compared with the release's published checksums when they are kept beside the store.",
		Customer:  "Keeps the release's SHA256SUMS beside the store and registers extensions deliberately.",
		Where:     []string{"quilzo ext", "quilzo self verify"}},
	{Control: "CP-2", Title: "Contingency Plan", Responsibility: Customer,
		Statement: "Quilzo reports a deployment with a single administrator, keeps a break-glass recovery for when every administrator token is lost, and its store can be verified object by object.",
		Customer:  "Writes and tests the contingency plan, including backups of the store.",
		Where:     []string{"quilzo auth recover", "quilzo verify"}},

	// -- identification and authentication -----------------------------------
	{Control: "IA-2", Title: "Identification and Authentication (Organizational Users)", Responsibility: Shared,
		Statement: "Every request is authenticated by a token, a passkey (WebAuthn) or single sign-on (OIDC or SAML 2.0); there are no passwords. Each audit record names the principal and whether the identity was verified.",
		Customer:  "Connects the identity provider and requires it where the organisation does.",
		Where:     []string{"internal/auth", "internal/webauthn", "internal/oidc", "internal/saml"}},
	{Control: "IA-2(1)", Title: "Multi-factor Authentication to Privileged Accounts", Responsibility: Shared,
		Statement: "Administrators can sign in with passkeys, or through single sign-on, where a SAML provider can be required to report multi-factor authentication (AuthnContext); single sign-on can be required for a whole email domain, and a session moved to another device or country must confirm its person again.",
		Customer:  "Requires passkeys or single sign-on for administrators.",
		Where:     []string{"/passkeys", "/sso"}},
	{Control: "IA-2(8)", Title: "Access to Accounts — Replay Resistant", Responsibility: Shared,
		Statement: "Passkeys are replay resistant by design, and SAML and OIDC responses are checked against a replay store. A token is a bearer credential: sessions made from one are short, bound to where they were issued, and revoked on sign-out.",
		Customer:  "Prefers passkeys and single sign-on to tokens for people.",
		Where:     []string{"internal/webauthn", "internal/saml"}},
	{Control: "IA-5", Title: "Authenticator Management", Responsibility: Shared,
		Statement: "Tokens are 256 random bits, shown once, stored only as a hash, expire within token.ttl.max, and can be revoked singly or with every session made from them; passkeys are registered per device and can be removed. The longest life is the organisation's parameter ia-05_odp.01.",
		Customer:  "Revokes credentials that are lost or no longer needed.",
		Where:     []string{"quilzo token", "/passkeys"}},
	{Control: "IA-5(1)", Title: "Password-based Authentication", Responsibility: Quilzo,
		Statement: "Quilzo has no passwords to guess, reuse or reset. The rules this control sets for passwords are applied to tokens instead: a default and a maximum lifetime, and rate-limited failures.",
		Where:     []string{"token.ttl.default", "token.ttl.max"}},
	{Control: "IA-5(2)", Title: "Public Key-based Authentication", Responsibility: Shared,
		Statement: "Identity providers' signing keys are pinned from their metadata, signatures are verified with SHA-256 or stronger, and certificates nearing expiry are reported.",
		Customer:  "Rotates identity-provider certificates before they expire.",
		Where:     []string{"internal/saml", "internal/oidc"}},
	{Control: "IA-11", Title: "Re-authentication", Responsibility: Quilzo,
		Statement: "A session ends after session.max and must be signed into again; a session used from another device or country is held until its person confirms it.",
		Where:     []string{"internal/admin", "internal/auth"}},

	// -- incident response, planning, privacy --------------------------------
	{Control: "IR-4", Title: "Incident Handling", Responsibility: Shared,
		Statement: "Cases record a declared incident, its findings, the decisions that start regulatory clocks and what is due, playbooks of steps, and actions on other systems approved by a second person; the shield contains attacks on Quilzo itself automatically and reversibly.",
		Customer:  "Runs the incident response process and its decisions.",
		Where:     []string{"quilzo incident", "/security/cases", "/security/shield"}},
	{Control: "PL-4", Title: "Rules of Behavior", Responsibility: Customer,
		Statement: "Quilzo tells the public what its automated assistants are and publishes the site's accessibility statement; it does not hold the organisation's rules of behaviour.",
		Customer:  "Writes the rules of behaviour and has users acknowledge them."},
	{Control: "PM-30", Title: "Supply Chain Risk Management Strategy", Responsibility: Customer,
		Statement: "Quilzo has one dependency, the Go standard library, describes itself in a bill of materials, marks where published content came from, and strips embedded metadata from images.",
		Customer:  "Sets the organisation's supply chain risk management strategy."},
	{Control: "PT-2", Title: "Authority to Process Personally Identifiable Information", Responsibility: Shared,
		Statement: "Each form names the lawful basis it collects on, from GDPR Article 6(1)'s six, and a consent form needs a box the person ticks; the posture scan and the site report name forms that state none.",
		Customer:  "Chooses the basis that is true for each form.",
		Where:     []string{"/forms", "/security/site"}},
	{Control: "PT-3", Title: "Personally Identifiable Information Processing Purposes", Responsibility: Shared,
		Statement: "Each form states what its answers are for, and submissions are kept for the period the form declares and then deleted.",
		Customer:  "States true purposes and periods.",
		Where:     []string{"/forms"}},
	{Control: "PT-5", Title: "Privacy Notice", Responsibility: Shared,
		Statement: "Before a person sends a form they are shown its notice, its purpose, its lawful basis and how long their answers are kept, wherever the form appears and in the description a browser's agent reads.",
		Customer:  "Writes the notice.",
		Where:     []string{"internal/form", "internal/public"}},

	// -- risk, acquisition ----------------------------------------------------
	{Control: "RA-5", Title: "Vulnerability Monitoring and Scanning", Responsibility: Shared,
		Statement: "This binary is checked hourly against an embedded, updatable snapshot of the Go vulnerability database, decided by which affected functions are actually linked into it; templates and content are scanned for injection and leaked credentials; the vulnerability workbench ranks the estate's findings.",
		Customer:  "Keeps the vulnerability database current and acts on findings.",
		Where:     []string{"quilzo self", "quilzo scan", "/security/vulns"}},
	{Control: "SA-9", Title: "External System Services", Responsibility: Shared,
		Statement: "Every outbound connection carries a declared purpose and can be switched off together (offline mode); a model hosted outside the organisation's network is reported, because what it is sent leaves.",
		Customer:  "Approves the external services used, including model providers.",
		Where:     []string{"internal/egress", "network.mode"}},
	{Control: "SA-15(13)", Title: "Logging Syntax", Responsibility: Quilzo,
		Statement: "Audit records have one fixed JSON schema, one record per line, carrying the AU-3 fields; a test keeps any detail field named for a key or secret out of the code, and principals are pseudonymised when records are exported.",
		Where:     []string{"internal/audit", "internal/siem"}},
	{Control: "SA-24", Title: "Design For Cyber Resiliency", Responsibility: Quilzo,
		Statement: "Quilzo protects itself without waiting for a person: reversible, self-expiring protections chosen by declared playbooks (block, slow, switch a feature off, lock the admin to strong sign-in, freeze publishing, pause an agent, cut a model route), features reached by a known flaw switched off until it is fixed, weakened settings put back, and decoy credentials that reveal whoever uses them.",
		Where:     []string{"internal/shield", "internal/selfvuln"}},

	// -- system and communications protection --------------------------------
	{Control: "SC-5", Title: "Denial-of-service Protection", Responsibility: Shared,
		Statement: "The API is rate-limited per token; sign-in failures are throttled; the shield slows or blocks a source that floods a feature, with a budget per source.",
		Customer:  "Provides network-level protection in front of the site.",
		Where:     []string{"api.rate.per_minute", "internal/shield"}},
	{Control: "SC-7", Title: "Boundary Protection", Responsibility: Shared,
		Statement: "The public site and the admin are separate processes on separate addresses; forwarded addresses are believed only from named proxies; outbound connections are tagged by purpose and refused to private, loopback and cloud-metadata addresses unless intended.",
		Customer:  "Places the admin behind the organisation's boundary and names the proxies in front.",
		Where:     []string{"internal/fetch", "internal/egress", "network.trusted_proxies"}},
	{Control: "SC-8", Title: "Transmission Confidentiality and Integrity", Responsibility: Shared,
		Statement: "Quilzo is served behind a proxy that terminates TLS: it marks its cookies Secure when told TLS ends in front of it, can send Strict-Transport-Security, and its own outbound connections use TLS 1.2 or later.",
		Customer:  "Terminates TLS in front of the site and the admin.",
		Where:     []string{"site.hsts", "admin.behind_tls_proxy"}},
	{Control: "SC-8(1)", Title: "Cryptographic Protection", Responsibility: Shared,
		Statement: "Quilzo's outbound connections are protected by TLS 1.2 or later from Go's standard library, with its default cipher suites.",
		Customer:  "Configures TLS on the proxy that terminates inbound connections."},
	{Control: "SC-12", Title: "Cryptographic Key Establishment and Management", Responsibility: Shared,
		Statement: "Keys are generated from the operating system's random source; the encryption keyring can add a key and rewrap stored objects under it; the log's signing key is written readable by its owner only.",
		Customer:  "Protects and backs up the keyring and signing keys, or supplies them from a key manager.",
		Where:     []string{"quilzo vault", "internal/vault"}},
	{Control: "SC-13", Title: "Cryptographic Protection", Responsibility: Quilzo,
		Statement: "Cryptography is Go's standard library only: SHA-256/384/512, HMAC-SHA256, AES-256-GCM, Ed25519, ECDSA, RSA for verifying others' signatures, ML-DSA-65 for post-quantum signatures, and TLS 1.2+. Each use is listed in the cryptographic inventory with its quantum status.",
		Where:     []string{"quilzo compliance crypto"}},
	{Control: "SC-17", Title: "Public Key Infrastructure Certificates", Responsibility: Shared,
		Statement: "Certificates from identity providers are pinned and reported before they expire.",
		Customer:  "Obtains and renews certificates."},
	{Control: "SC-18", Title: "Mobile Code", Responsibility: Quilzo,
		Statement: "Published pages carry a Content-Security-Policy generated from what the content actually references; the template language cannot emit script, and the one construct that emits markup unescaped is reported. The admin runs one first-party script, allowed by a per-response nonce.",
		Where:     []string{"quilzo csp", "internal/csp"}},
	{Control: "SC-23", Title: "Session Authenticity", Responsibility: Quilzo,
		Statement: "Admin sessions are server-side credentials in HttpOnly, SameSite cookies; cross-site writes are refused by origin; a session is bound to the device and country it was issued in and held for confirmation if it moves.",
		Where:     []string{"internal/admin"}},
	{Control: "SC-28", Title: "Protection of Information at Rest", Responsibility: Shared,
		Statement: "With a keyring configured, every object in the store is encrypted with AES-256-GCM under a key that can be rotated; secrets for connected systems are sealed the same way.",
		Customer:  "Configures the keyring and keeps its key off the machine's disk or in a key manager.",
		Where:     []string{"quilzo vault", "internal/vault"}},
	{Control: "SC-39", Title: "Process Isolation", Responsibility: Quilzo,
		Statement: "The public site, the admin and the log collector are separate processes; an extension runs as a child process with an empty environment, a time limit and, on Linux 5.13 or later, a Landlock sandbox that limits what it can read and, from kernel ABI 4, whether it can open TCP connections.",
		Where:     []string{"internal/sandbox", "internal/ext"}},

	// -- system and information integrity ------------------------------------
	{Control: "SI-2", Title: "Flaw Remediation", Responsibility: Shared,
		Statement: "Each known flaw in the Go release this binary was built with is decided by whether what it names is linked in: cleared with a VEX statement, contained by switching off the features that reach it, or reported for an upgrade.",
		Customer:  "Upgrades to the release that fixes a reported flaw.",
		Where:     []string{"quilzo self check", "quilzo self vex"}},
	{Control: "SI-2(7)", Title: "Root Cause Analysis", Responsibility: Customer,
		Statement: "Cases keep a declared incident's findings, decisions and notes together, and the shield records which playbook acted and whether a person judged it right, which is the material a root cause analysis starts from.",
		Customer:  "Conducts the analysis and tracks its actions."},
	{Control: "SI-4", Title: "System Monitoring", Responsibility: Shared,
		Statement: "Signals from the sites, the admin, the API, sign-ins and agents feed the shield's playbooks and the detections; collected events from other systems feed the same detections; the browser's reports of blocked content arrive at a reporting endpoint.",
		Customer:  "Chooses what else to collect and who watches the queue.",
		Where:     []string{"internal/shield", "internal/detect", "/security/events"}},
	{Control: "SI-7", Title: "Software, Firmware, and Information Integrity", Responsibility: Quilzo,
		Statement: "Content is stored by its hash and every object can be re-hashed; the audit log is chained and signed; provenance records say how each page came to be and are reported when stale; the running binary is compared with the one the store last saw and with the release; extensions must match their pinned hash.",
		Where:     []string{"quilzo verify", "quilzo provenance", "quilzo self verify"}},
	{Control: "SI-10", Title: "Information Input Validation", Responsibility: Quilzo,
		Statement: "Content must satisfy its bound type before it is stored; a draft that fails accessibility, carries a card number or a credential, makes an unsubstantiated claim or references a missing page is refused at publishing; agents treat what they read as untrusted and are evaluated against planted instructions.",
		Where:     []string{"internal/schema", "internal/gate", "internal/agent"}},
	{Control: "SI-12", Title: "Information Management and Retention", Responsibility: Shared,
		Statement: "Form submissions are deleted after their form's period by both servers, and the posture scan reports any that outlive it; embedded metadata is stripped from uploaded images.",
		Customer:  "Sets periods that match the organisation's records policy.",
		Where:     []string{"internal/form", "media.strip_metadata"}},

	// -- supply chain ---------------------------------------------------------
	{Control: "SR-4", Title: "Provenance", Responsibility: Quilzo,
		Statement: "The binary records how it was built (module, version, build settings) and exports it as a bill of materials; published content and media carry provenance in the C2PA and IPTC vocabularies.",
		Where:     []string{"quilzo compliance sbom", "quilzo provenance", "internal/c2pa"}},
}
